from collections.abc import Mapping
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ICookieManager(Protocol):
    def get_cookie_info_for_ytdlp(self) -> dict[str, Any] | None: ...

    def get_current_cookie_path(self) -> str | None: ...

    def get_cookies(self, domain: str) -> Mapping[str, str]: ...

    def needs_regeneration(self, domain: str, max_age_hours: int) -> bool: ...

    def get_cookie_file_path(self, domain: str) -> str | None: ...
